server:
  port: ${PORT}

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    show_sql: true

logging:
  level:
    org.springframework.security: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER:com.maintenops.nvcc}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:900}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_TOKEN_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}

app:
  cors:
    front-end-url: ${FRONTEND_URL}